//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Superbar.Adapters
{
    
    public class IMessageEventHandlerContractToViewAddInAdapter
    {
        private Start9.Api.Contracts.IMessageEventHandlerContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        public IMessageEventHandlerContractToViewAddInAdapter(Start9.Api.Contracts.IMessageEventHandlerContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public void Handler(object sender, Superbar.Views.MessageReceivedEventArgs args)
        {
            _contract.Handler(Superbar.Adapters.MessageReceivedEventArgsAddInAdapter.ViewToContractAdapter(args));
        }
        internal Start9.Api.Contracts.IMessageEventHandlerContract GetSourceContract()
        {
            return _contract;
        }
    }
}

